import '../styles/globals.css'
import { Inter } from 'next/font/google'
import ContextProvider from '@store/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Illuminated Creativity',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
